on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy build to target
        uses: actions/download-artifact@v4
        run: echo "Deploying build:${{ inputs.build_id }} to target:${{ inputs.deploy_target }}"
